source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.1'

gem 'sqlite3'
gem 'rake'
gem 'sinatra'
gem 'sinatra-activerecord', require: %w(sinatra/activerecord)

group :development, :test do
  gem 'byebug'
end
